package org.lwjgl.opengl;

/** LWJGL GL30 for the browser (see retro.gl.GLEmu). Constants from LWJGL 2.9.3. */
public final class GL30 {
    public static final int GL_MAJOR_VERSION = 0x821b;
    public static final int GL_MINOR_VERSION = 0x821c;
    public static final int GL_NUM_EXTENSIONS = 0x821d;
    public static final int GL_CONTEXT_FLAGS = 0x821e;
    public static final int GL_CONTEXT_FLAG_FORWARD_COMPATIBLE_BIT = 1;
    public static final int GL_DEPTH_BUFFER = 0x8223;
    public static final int GL_STENCIL_BUFFER = 0x8224;
    public static final int GL_COMPRESSED_RED = 0x8225;
    public static final int GL_COMPRESSED_RG = 0x8226;
    public static final int GL_COMPARE_REF_TO_TEXTURE = 0x884e;
    public static final int GL_CLIP_DISTANCE0 = 0x3000;
    public static final int GL_CLIP_DISTANCE1 = 0x3001;
    public static final int GL_CLIP_DISTANCE2 = 0x3002;
    public static final int GL_CLIP_DISTANCE3 = 0x3003;
    public static final int GL_CLIP_DISTANCE4 = 0x3004;
    public static final int GL_CLIP_DISTANCE5 = 0x3005;
    public static final int GL_CLIP_DISTANCE6 = 0x3006;
    public static final int GL_CLIP_DISTANCE7 = 0x3007;
    public static final int GL_MAX_CLIP_DISTANCES = 3378;
    public static final int GL_MAX_VARYING_COMPONENTS = 0x8b4b;
    public static final int GL_BUFFER_ACCESS_FLAGS = 0x911f;
    public static final int GL_BUFFER_MAP_LENGTH = 0x9120;
    public static final int GL_BUFFER_MAP_OFFSET = 0x9121;
    public static final int GL_VERTEX_ATTRIB_ARRAY_INTEGER = 0x88fd;
    public static final int GL_SAMPLER_BUFFER = 0x8dc2;
    public static final int GL_SAMPLER_CUBE_SHADOW = 0x8dc5;
    public static final int GL_UNSIGNED_INT_VEC2 = 0x8dc6;
    public static final int GL_UNSIGNED_INT_VEC3 = 0x8dc7;
    public static final int GL_UNSIGNED_INT_VEC4 = 0x8dc8;
    public static final int GL_INT_SAMPLER_1D = 0x8dc9;
    public static final int GL_INT_SAMPLER_2D = 0x8dca;
    public static final int GL_INT_SAMPLER_3D = 0x8dcb;
    public static final int GL_INT_SAMPLER_CUBE = 0x8dcc;
    public static final int GL_INT_SAMPLER_2D_RECT = 0x8dcd;
    public static final int GL_INT_SAMPLER_1D_ARRAY = 0x8dce;
    public static final int GL_INT_SAMPLER_2D_ARRAY = 0x8dcf;
    public static final int GL_INT_SAMPLER_BUFFER = 0x8dd0;
    public static final int GL_UNSIGNED_INT_SAMPLER_1D = 0x8dd1;
    public static final int GL_UNSIGNED_INT_SAMPLER_2D = 0x8dd2;
    public static final int GL_UNSIGNED_INT_SAMPLER_3D = 0x8dd3;
    public static final int GL_UNSIGNED_INT_SAMPLER_CUBE = 0x8dd4;
    public static final int GL_UNSIGNED_INT_SAMPLER_2D_RECT = 0x8dd5;
    public static final int GL_UNSIGNED_INT_SAMPLER_1D_ARRAY = 0x8dd6;
    public static final int GL_UNSIGNED_INT_SAMPLER_2D_ARRAY = 0x8dd7;
    public static final int GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8dd8;
    public static final int GL_MIN_PROGRAM_TEXEL_OFFSET = 0x8904;
    public static final int GL_MAX_PROGRAM_TEXEL_OFFSET = 0x8905;
    public static final int GL_QUERY_WAIT = 0x8e13;
    public static final int GL_QUERY_NO_WAIT = 0x8e14;
    public static final int GL_QUERY_BY_REGION_WAIT = 0x8e15;
    public static final int GL_QUERY_BY_REGION_NO_WAIT = 0x8e16;
    public static final int GL_MAP_READ_BIT = 1;
    public static final int GL_MAP_WRITE_BIT = 2;
    public static final int GL_MAP_INVALIDATE_RANGE_BIT = 4;
    public static final int GL_MAP_INVALIDATE_BUFFER_BIT = 8;
    public static final int GL_MAP_FLUSH_EXPLICIT_BIT = 16;
    public static final int GL_MAP_UNSYNCHRONIZED_BIT = 32;
    public static final int GL_CLAMP_VERTEX_COLOR = 0x891a;
    public static final int GL_CLAMP_FRAGMENT_COLOR = 0x891b;
    public static final int GL_CLAMP_READ_COLOR = 0x891c;
    public static final int GL_FIXED_ONLY = 0x891d;
    public static final int GL_DEPTH_COMPONENT32F = 0x8cac;
    public static final int GL_DEPTH32F_STENCIL8 = 0x8cad;
    public static final int GL_FLOAT_32_UNSIGNED_INT_24_8_REV = 0x8dad;
    public static final int GL_TEXTURE_RED_TYPE = 0x8c10;
    public static final int GL_TEXTURE_GREEN_TYPE = 0x8c11;
    public static final int GL_TEXTURE_BLUE_TYPE = 0x8c12;
    public static final int GL_TEXTURE_ALPHA_TYPE = 0x8c13;
    public static final int GL_TEXTURE_LUMINANCE_TYPE = 0x8c14;
    public static final int GL_TEXTURE_INTENSITY_TYPE = 0x8c15;
    public static final int GL_TEXTURE_DEPTH_TYPE = 0x8c16;
    public static final int GL_UNSIGNED_NORMALIZED = 0x8c17;
    public static final int GL_RGBA32F = 0x8814;
    public static final int GL_RGB32F = 0x8815;
    public static final int GL_ALPHA32F = 0x8816;
    public static final int GL_RGBA16F = 0x881a;
    public static final int GL_RGB16F = 0x881b;
    public static final int GL_ALPHA16F = 0x881c;
    public static final int GL_R11F_G11F_B10F = 0x8c3a;
    public static final int GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8c3b;
    public static final int GL_RGB9_E5 = 0x8c3d;
    public static final int GL_UNSIGNED_INT_5_9_9_9_REV = 0x8c3e;
    public static final int GL_TEXTURE_SHARED_SIZE = 0x8c3f;
    public static final int GL_FRAMEBUFFER = 0x8d40;
    public static final int GL_READ_FRAMEBUFFER = 0x8ca8;
    public static final int GL_DRAW_FRAMEBUFFER = 0x8ca9;
    public static final int GL_RENDERBUFFER = 0x8d41;
    public static final int GL_STENCIL_INDEX1 = 0x8d46;
    public static final int GL_STENCIL_INDEX4 = 0x8d47;
    public static final int GL_STENCIL_INDEX8 = 0x8d48;
    public static final int GL_STENCIL_INDEX16 = 0x8d49;
    public static final int GL_RENDERBUFFER_WIDTH = 0x8d42;
    public static final int GL_RENDERBUFFER_HEIGHT = 0x8d43;
    public static final int GL_RENDERBUFFER_INTERNAL_FORMAT = 0x8d44;
    public static final int GL_RENDERBUFFER_RED_SIZE = 0x8d50;
    public static final int GL_RENDERBUFFER_GREEN_SIZE = 0x8d51;
    public static final int GL_RENDERBUFFER_BLUE_SIZE = 0x8d52;
    public static final int GL_RENDERBUFFER_ALPHA_SIZE = 0x8d53;
    public static final int GL_RENDERBUFFER_DEPTH_SIZE = 0x8d54;
    public static final int GL_RENDERBUFFER_STENCIL_SIZE = 0x8d55;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_TYPE = 0x8cd0;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_OBJECT_NAME = 0x8cd1;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LEVEL = 0x8cd2;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_CUBE_MAP_FACE = 0x8cd3;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_COLOR_ENCODING = 0x8210;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_COMPONENT_TYPE = 0x8211;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_RED_SIZE = 0x8212;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_GREEN_SIZE = 0x8213;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_BLUE_SIZE = 0x8214;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_ALPHA_SIZE = 0x8215;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_DEPTH_SIZE = 0x8216;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_STENCIL_SIZE = 0x8217;
    public static final int GL_FRAMEBUFFER_DEFAULT = 0x8218;
    public static final int GL_INDEX = 0x8222;
    public static final int GL_COLOR_ATTACHMENT0 = 0x8ce0;
    public static final int GL_COLOR_ATTACHMENT1 = 0x8ce1;
    public static final int GL_COLOR_ATTACHMENT2 = 0x8ce2;
    public static final int GL_COLOR_ATTACHMENT3 = 0x8ce3;
    public static final int GL_COLOR_ATTACHMENT4 = 0x8ce4;
    public static final int GL_COLOR_ATTACHMENT5 = 0x8ce5;
    public static final int GL_COLOR_ATTACHMENT6 = 0x8ce6;
    public static final int GL_COLOR_ATTACHMENT7 = 0x8ce7;
    public static final int GL_COLOR_ATTACHMENT8 = 0x8ce8;
    public static final int GL_COLOR_ATTACHMENT9 = 0x8ce9;
    public static final int GL_COLOR_ATTACHMENT10 = 0x8cea;
    public static final int GL_COLOR_ATTACHMENT11 = 0x8ceb;
    public static final int GL_COLOR_ATTACHMENT12 = 0x8cec;
    public static final int GL_COLOR_ATTACHMENT13 = 0x8ced;
    public static final int GL_COLOR_ATTACHMENT14 = 0x8cee;
    public static final int GL_COLOR_ATTACHMENT15 = 0x8cef;
    public static final int GL_DEPTH_ATTACHMENT = 0x8d00;
    public static final int GL_STENCIL_ATTACHMENT = 0x8d20;
    public static final int GL_DEPTH_STENCIL_ATTACHMENT = 0x821a;
    public static final int GL_FRAMEBUFFER_COMPLETE = 0x8cd5;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_ATTACHMENT = 0x8cd6;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_MISSING_ATTACHMENT = 0x8cd7;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_DRAW_BUFFER = 0x8cdb;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_READ_BUFFER = 0x8cdc;
    public static final int GL_FRAMEBUFFER_UNSUPPORTED = 0x8cdd;
    public static final int GL_FRAMEBUFFER_UNDEFINED = 0x8219;
    public static final int GL_FRAMEBUFFER_BINDING = 0x8ca6;
    public static final int GL_RENDERBUFFER_BINDING = 0x8ca7;
    public static final int GL_MAX_COLOR_ATTACHMENTS = 0x8cdf;
    public static final int GL_MAX_RENDERBUFFER_SIZE = 0x84e8;
    public static final int GL_INVALID_FRAMEBUFFER_OPERATION = 1286;
    public static final int GL_HALF_FLOAT = 0x140b;
    public static final int GL_RENDERBUFFER_SAMPLES = 0x8cab;
    public static final int GL_FRAMEBUFFER_INCOMPLETE_MULTISAMPLE = 0x8d56;
    public static final int GL_MAX_SAMPLES = 0x8d57;
    public static final int GL_DRAW_FRAMEBUFFER_BINDING = 0x8ca6;
    public static final int GL_READ_FRAMEBUFFER_BINDING = 0x8caa;
    public static final int GL_RGBA_INTEGER_MODE = 0x8d9e;
    public static final int GL_RGBA32UI = 0x8d70;
    public static final int GL_RGB32UI = 0x8d71;
    public static final int GL_ALPHA32UI = 0x8d72;
    public static final int GL_RGBA16UI = 0x8d76;
    public static final int GL_RGB16UI = 0x8d77;
    public static final int GL_ALPHA16UI = 0x8d78;
    public static final int GL_RGBA8UI = 0x8d7c;
    public static final int GL_RGB8UI = 0x8d7d;
    public static final int GL_ALPHA8UI = 0x8d7e;
    public static final int GL_RGBA32I = 0x8d82;
    public static final int GL_RGB32I = 0x8d83;
    public static final int GL_ALPHA32I = 0x8d84;
    public static final int GL_RGBA16I = 0x8d88;
    public static final int GL_RGB16I = 0x8d89;
    public static final int GL_ALPHA16I = 0x8d8a;
    public static final int GL_RGBA8I = 0x8d8e;
    public static final int GL_RGB8I = 0x8d8f;
    public static final int GL_ALPHA8I = 0x8d90;
    public static final int GL_RED_INTEGER = 0x8d94;
    public static final int GL_GREEN_INTEGER = 0x8d95;
    public static final int GL_BLUE_INTEGER = 0x8d96;
    public static final int GL_ALPHA_INTEGER = 0x8d97;
    public static final int GL_RGB_INTEGER = 0x8d98;
    public static final int GL_RGBA_INTEGER = 0x8d99;
    public static final int GL_BGR_INTEGER = 0x8d9a;
    public static final int GL_BGRA_INTEGER = 0x8d9b;
    public static final int GL_TEXTURE_1D_ARRAY = 0x8c18;
    public static final int GL_TEXTURE_2D_ARRAY = 0x8c1a;
    public static final int GL_PROXY_TEXTURE_2D_ARRAY = 0x8c1b;
    public static final int GL_PROXY_TEXTURE_1D_ARRAY = 0x8c19;
    public static final int GL_TEXTURE_BINDING_1D_ARRAY = 0x8c1c;
    public static final int GL_TEXTURE_BINDING_2D_ARRAY = 0x8c1d;
    public static final int GL_MAX_ARRAY_TEXTURE_LAYERS = 0x88ff;
    public static final int GL_COMPARE_REF_DEPTH_TO_TEXTURE = 0x884e;
    public static final int GL_FRAMEBUFFER_ATTACHMENT_TEXTURE_LAYER = 0x8cd4;
    public static final int GL_SAMPLER_1D_ARRAY = 0x8dc0;
    public static final int GL_SAMPLER_2D_ARRAY = 0x8dc1;
    public static final int GL_SAMPLER_1D_ARRAY_SHADOW = 0x8dc3;
    public static final int GL_SAMPLER_2D_ARRAY_SHADOW = 0x8dc4;
    public static final int GL_DEPTH_STENCIL = 0x84f9;
    public static final int GL_UNSIGNED_INT_24_8 = 0x84fa;
    public static final int GL_DEPTH24_STENCIL8 = 0x88f0;
    public static final int GL_TEXTURE_STENCIL_SIZE = 0x88f1;
    public static final int GL_COMPRESSED_RED_RGTC1 = 0x8dbb;
    public static final int GL_COMPRESSED_SIGNED_RED_RGTC1 = 0x8dbc;
    public static final int GL_COMPRESSED_RG_RGTC2 = 0x8dbd;
    public static final int GL_COMPRESSED_SIGNED_RG_RGTC2 = 0x8dbe;
    public static final int GL_R8 = 0x8229;
    public static final int GL_R16 = 0x822a;
    public static final int GL_RG8 = 0x822b;
    public static final int GL_RG16 = 0x822c;
    public static final int GL_R16F = 0x822d;
    public static final int GL_R32F = 0x822e;
    public static final int GL_RG16F = 0x822f;
    public static final int GL_RG32F = 0x8230;
    public static final int GL_R8I = 0x8231;
    public static final int GL_R8UI = 0x8232;
    public static final int GL_R16I = 0x8233;
    public static final int GL_R16UI = 0x8234;
    public static final int GL_R32I = 0x8235;
    public static final int GL_R32UI = 0x8236;
    public static final int GL_RG8I = 0x8237;
    public static final int GL_RG8UI = 0x8238;
    public static final int GL_RG16I = 0x8239;
    public static final int GL_RG16UI = 0x823a;
    public static final int GL_RG32I = 0x823b;
    public static final int GL_RG32UI = 0x823c;
    public static final int GL_RG = 0x8227;
    public static final int GL_RG_INTEGER = 0x8228;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER = 0x8c8e;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER_START = 0x8c84;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER_SIZE = 0x8c85;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER_BINDING = 0x8c8f;
    public static final int GL_INTERLEAVED_ATTRIBS = 0x8c8c;
    public static final int GL_SEPARATE_ATTRIBS = 0x8c8d;
    public static final int GL_PRIMITIVES_GENERATED = 0x8c87;
    public static final int GL_TRANSFORM_FEEDBACK_PRIMITIVES_WRITTEN = 0x8c88;
    public static final int GL_RASTERIZER_DISCARD = 0x8c89;
    public static final int GL_MAX_TRANSFORM_FEEDBACK_INTERLEAVED_COMPONENTS = 0x8c8a;
    public static final int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_ATTRIBS = 0x8c8b;
    public static final int GL_MAX_TRANSFORM_FEEDBACK_SEPARATE_COMPONENTS = 0x8c80;
    public static final int GL_TRANSFORM_FEEDBACK_VARYINGS = 0x8c83;
    public static final int GL_TRANSFORM_FEEDBACK_BUFFER_MODE = 0x8c7f;
    public static final int GL_TRANSFORM_FEEDBACK_VARYING_MAX_LENGTH = 0x8c76;
    public static final int GL_VERTEX_ARRAY_BINDING = 0x85b5;
    public static final int GL_FRAMEBUFFER_SRGB = 0x8db9;
    public static final int GL_FRAMEBUFFER_SRGB_CAPABLE = 0x8dba;

    private GL30() {
    }

    public static void glGenerateMipmap(int target) { retro.gl.GLEmu.generateMipmap(); }

    public static int glGenFramebuffers() { return EXTFramebufferObject.glGenFramebuffersEXT(); }
    public static void glDeleteFramebuffers(int id) { EXTFramebufferObject.glDeleteFramebuffersEXT(id); }
    public static void glBindFramebuffer(int target, int id) { EXTFramebufferObject.glBindFramebufferEXT(target, id); }
    public static void glFramebufferTexture2D(int target, int attachment, int textarget, int texture, int level) {
        EXTFramebufferObject.glFramebufferTexture2DEXT(target, attachment, textarget, texture, level);
    }
    public static int glGenRenderbuffers() { return EXTFramebufferObject.glGenRenderbuffersEXT(); }
    public static void glDeleteRenderbuffers(int id) { EXTFramebufferObject.glDeleteRenderbuffersEXT(id); }
    public static void glBindRenderbuffer(int target, int id) { EXTFramebufferObject.glBindRenderbufferEXT(target, id); }
    public static void glRenderbufferStorage(int target, int internalFormat, int width, int height) {
        EXTFramebufferObject.glRenderbufferStorageEXT(target, internalFormat, width, height);
    }
    public static void glFramebufferRenderbuffer(int target, int attachment, int rbTarget, int renderbuffer) {
        EXTFramebufferObject.glFramebufferRenderbufferEXT(target, attachment, rbTarget, renderbuffer);
    }
    public static int glCheckFramebufferStatus(int target) { return EXTFramebufferObject.glCheckFramebufferStatusEXT(target); }
}
